### ISSUE TITLE
Website crashes sporadically

### ISSUE THREAD

**Issue by micheljung** [FAForever/website#107] opened 2017-08-16 21:09 UTC
I put the log here: http://content.faforever.com/website.log

Relevant part is probably this:
```
 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
 ^

 SyntaxError: Unexpected token < in JSON at position 0
     at JSON.parse (<anonymous>)
     at Request._callback (/code/express.js:141:21)
     at Request.self.callback (/code/node_modules/request/request.js:186:22)
     at emitTwo (events.js:106:13)
     at Request.emit (events.js:191:7)
     at Request.<anonymous> (/code/node_modules/request/request.js:1081:10)
     at emitOne (events.js:96:13)
     at Request.emit (events.js:188:7)
     at IncomingMessage.<anonymous> (/code/node_modules/request/request.js:1001:12)
     at IncomingMessage.g (events.js:292:16)
     at emitNone (events.js:91:20)
     at IncomingMessage.emit (events.js:185:7)
     at endReadableNT (_stream_readable.js:974:12)
     at _combinedTickCallback (internal/process/next_tick.js:74:11)
     at process._tickCallback (internal/process/next_tick.js:98:9)

 npm info lifecycle website@0.0.0~start: Failed to exec start script
 npm ERR! Linux 3.13.0-76-generic
 npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
 npm ERR! node v7.2.1
 npm ERR! npm  v3.10.10
 npm ERR! code ELIFECYCLE
 npm ERR! website@0.0.0 start: `node express.js`
 npm ERR! Exit status 1
 npm ERR!
 npm ERR! Failed at the website@0.0.0 start script 'node express.js'.
 npm ERR! Make sure you have the latest version of node.js and npm installed.
 npm ERR! If you do, this is most likely a problem with the website package,
 npm ERR! not with npm itself.
 npm ERR! Tell the author that this fails on your system:
 npm ERR!     node express.js
 npm ERR! You can get information on how to open an issue for this project with:
 npm ERR!     npm bugs website
 npm ERR! Or if that isn't available, you can get their info via:
 npm ERR!     npm owner ls website
 npm ERR! There is likely additional logging output above.
```

But there's also:

```
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
```

**Comment by Sheeo** [comment] 2017-10-30 09:04
Duplicate of https://github.com/FAForever/website/issues/95

**Closed by Sheeo** 2017-10-30 09:04 UTC
Labels: bug
