### ISSUE TITLE
Report form autocomplete = broken

### ISSUE THREAD

**Issue by Viba** [FAForever/website#233] opened 2020-05-24 15:26 UTC
Users are unable to report other users due to the autocomplete not autocompleting properly.

e.g. trying to report "Kalvirox" it returns results for the first two and three letters like below (with weird spaces), then nothing. If the form doesn't find a valid player it doesn't allow filing a report. This is quite important to moderation.

![image](https://user-images.githubusercontent.com/3510353/82757934-1b0e8300-9dec-11ea-8daa-ec0caf2e7de1.png)
![image](https://user-images.githubusercontent.com/3510353/82757940-206bcd80-9dec-11ea-9b92-c70ec17be0da.png)

**Comment by Brutus5000** [comment] 2020-05-24 18:13
It works but it is broken by design.
![image](https://user-images.githubusercontent.com/6843462/82761429-c58da280-9dfa-11ea-9317-3b44a54b12bc.png)

I looked up the code and it seems to work like this:
It only collects player names of the players who played a game in the last 24 hours at the moment of startup and never refreshes it.

**Comment by 1-alex98** [comment] 2020-05-24 19:19
I will just check if I am reportabe and if not I can do what I want XD @Brutus5000 when is the next restart?

**Comment by Brutus5000** [comment] 2020-05-24 19:25
Looks like it crashed 11 minutes ago and was restarted

**Comment by 1-alex98** [comment] 2020-05-24 20:17
Well it updates the names every 15 minutes

**Comment by norraxx** [comment] 2020-06-03 17:03
We shouldn't search inside the usernames with `LIKE %{}%`. It's very expensive operation.
`LIKE {}%` is much much faster.

**Comment by Rackover** [comment] 2022-04-07 09:24
You can submit a report even if the autocomplete does not include it now, so is that still a problem?
The suggestions when writing someone's name are incomplete because they only include players from the last 24 hours for performance/caching reasons, but this could be changed and/or extended if necessary - ultimately as long as we rely on caching it will result in passing a huge list of names  to the client/browser and making the page more heavy (or we could kill caching and fetch the names from the API as they are typed, realtime, but not sure how to do that with awesomplete)

**Comment by Brutus5000** [comment] 2022-04-07 19:33
Are we sure it is refreshed once per day? I think I didn't find anything related back then.

**Comment by Rackover** [comment] 2022-04-07 19:36
Every 15 minutes normally! https://github.com/FAForever/website/blob/develop/express.js#L293
Script is there : https://github.com/FAForever/website/blob/develop/scripts/getRecentUsers.js

Now only way to see if it actually runs on prod is to check website logs on prod. Locally it appears to work, but test server has no recent games so no players get updated on it! Also 15 minutes might be a bit long...

**Comment by Brutus5000** [comment] 2022-04-07 19:44
Would be good to log these jobs not only when the fail :)

**Comment by Rackover** [comment] 2022-04-07 19:52
> Would be good to log these jobs not only when the fail :)

there is logging in the normal behaviour look :  
```
    console.log(moment().format("DD-MM-YYYY - HH:mm:ss")  + ' - Updating the recent users...'); // When it starts
    console.log(moment().format("DD-MM-YYYY - HH:mm:ss") + ' - Recent players file created successfully'); // When it finishes
```

Could you look at prod logs and see if they're here?

**Comment by Brutus5000** [comment] 2022-04-07 19:56
It does work now. I'm pretty sure the log was mostly empty back then :shrug:

**Comment by Rackover** [comment] 2022-06-13 21:56
So is that... still an issue ? 😄

**Comment by fcaps** [comment] 2023-11-08 09:48
Still an issue😄
new design/layout, but autocomplete is still broken

**Comment by fcaps** [comment] 2023-12-01 20:56
finally fixed with https://github.com/FAForever/website/pull/504

**Closed as completed by fcaps** 2023-12-01 20:56 UTC
Labels: Bug
