### ISSUE TITLE
User rudyeckert can't manage his clan "tier 2"

### ISSUE THREAD

**Issue by norraxx** [FAForever/website#250] opened 2020-09-18 09:26 UTC
User `rudyeckert` can't manage his clan `tier 2`.

After clicking on manage clan he get an error.

https://media.discordapp.net/attachments/756334517458960434/756444543523749958/clan_managment.PNG

**Comment by 1-alex98** [comment] 2021-01-21 22:54
yes same here... on every clan i click

**Comment by 1-alex98** [comment] 2021-10-02 13:04
Works for me now... Please provide a way to reproduce

**Comment by MrRowey** [comment] 2022-03-22 10:35
#322

**Comment by Rackover** [comment] 2022-04-03 17:15
Is this still an issue?

**Comment by MrRowey** [comment] 2022-04-06 12:48
Closing Issues as it seems to be fixed in Current website version

**Closed as completed by MrRowey** 2022-04-06 12:48 UTC
Labels: Bug
